site_name: Rayfield
site_url: https://pamlib.github.io/rf/
repo_name: pamlib/rf
repo_url: https://github.com/pamlib/rf

theme:
  name: material
  language: en
  custom_dir: docs/assets/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Start: start/index.md
  - Lore: lore/index.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
